name: ğŸ¨ Tartufo ğŸ´â€â˜ ï¸

on: [push]

jobs:
  tartufo:
    name: Run Tartufo
    runs-on: ubuntu-latest
    steps:
    - uses: "actions/checkout@v2"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Python ğŸ
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Check for leaks ğŸ’¦
      run: |
        git pull --unshallow
        pip install tartufo
        tartufo --config tartufo.toml scan-local-repo .